version: '3.8'

services:
  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app  # Optional for development (keeps the code updated live)
    ports:
      - "8000:8000"
    env_file: .env  # Reference your .env file for environment variables
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
