name: CI/CD Pipeline to Deploy on VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VM via SSH using appleboy/ssh-action
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/andromeda/dkn/budidayaplus

          # Pull the latest code
          git pull origin main

          # Export environment variables from GitHub secrets to the VM
          export DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}

          # Write the environment variable to .env file (Optional if you want to ensure a .env file exists)
          echo "DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY" > .env

          # Stop the existing containers if they are running
          docker-compose down

          # Build the Docker images
          docker-compose build

          # Apply migrations inside the web container
          docker-compose run web python manage.py migrate

          # Collect static files
          docker-compose run web python manage.py collectstatic --noinput

          # Bring up the containers in detached mode
          docker-compose up -d

          # Optional: View the web container logs to ensure it's running
          docker-compose logs web
